## 12.6 应用-可验证的函数参数

- [x] demo

```js
function sum(a, b) {
    return a + b;
}

function validatorFunction(func, ...types) {
    return new Proxy(func, {
        apply(target, thisArgument, argumentsList) {
            types.forEach((t, i) => {
                const type = typeof argumentsList[i];
                if (type !== t) {
                    throw new TypeError(`第${i+1}个参数的数据类型要求是${t}`);
                }
            });
            return Reflect.apply(target, thisArgument, argumentsList);
        }
    });
}

const sumProxy = validatorFunction(sum, 'number', 'number');

console.log(sumProxy(1, 2));
console.log(sumProxy(1, '2')); // Uncaught TypeError: 第2个参数的数据类型要求是number
```

```
Reflect.apply(target, thisArgument, argumentsList);
[问] 为什么不return 后续的两条打印语句得到的是 undefined
[答] ... 这其实就是走代理呀, 如果理解了啥叫走代理, 应该都不会有这样的问题... 因为当我们调用 sumProxy() 的时候, 实际上就是在调用 apply, 也就是说, 我们调用 sumProxy 得到的返回值 就是 apply 中给我们返回的值, 若 apply 中设置不返回值的话, 那么默认返回的是 undefined
```

- [x] demo

```js
function sum(a, b) {
    return a + b;
}

function validatorFunction(func, ...types) {
    return function (...args) {
        types.forEach((t, i) => {
            const type = typeof args[i];
            if (type !== t) {
                throw new TypeError(`第${i+1}个参数的数据类型要求是${t}`);
            }
        });
        return func(...args);
    }
}

const sumProxy = validatorFunction(sum, 'number', 'number');

console.log(sumProxy(1, 2));
console.log(sumProxy(1, '2')); // Uncaught TypeError: 第2个参数的数据类型要求是number
```

> 多创建了一个函数 浪费内存


